spring.application.name=ms-security
spring.mongodb.database=db_security
spring.mongodb.uri=mongodb+srv://AlejandroDM:HannaH07@cluster0.qhzxqp5.mongodb.net/?appName=Cluster0
server.port=8081
jwt.secret=busesInteligentesClaveSecretaSuperSeguraParaFirmarTokensJWT2024XYZ!!
jwt.expiration=3600000
firebase.credentials.path=classpath:firebase-service-account.json