spring.application.name=ms-security
spring.config.import=optional:file:.env[.properties],optional:file:functions/ms-security/.env[.properties]
spring.mongodb.database=${MONGODB_DATABASE:db_security}
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/db_security}
server.port=${SERVER_PORT:8081}
jwt.secret=${JWT_SECRET:change-this-jwt-secret-in-env-before-prod}
jwt.expiration=${JWT_EXPIRATION:3600000}
firebase.credentials.path=classpath:firebase-service-account.json
